#!/usr/bin/env bash
# Your process displays "I am invincible!!!" when receiving a SIGTERM signal

# Set up signal handler for SIGTERM
trap 'echo "I am invincible!!!"' TERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
