#!/bin/bash

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
}

# Set up signal handler for SIGTERM
trap handle_sigterm SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
